const palette = {
	black: '#000000',
	white: '#ffffff',
	green: '#b2ffb7',
	pink: '#ffe6ff',
	purple: '#7800cc',
	blue: '#adfff5',
	vice_blue: '#0bd3d3',
	vice_pink: '#f890e7',
	vice_green: '#64e8ba',
	vice_grey: '#d0d0d0',
	neon_black: '#4f4f4f',
	neon_pink: '#ff778c',
	neon_purple: '#d087ff',
	neon_blue: '#56fbff',
	neon_green: '#66ff4b',
	light_black: '#2b2c35',
	grey: '#404149',
	light_grey: '#6a6b71',
	lighter_grey: '#95959a',
};
export const colors = {
	buttonPrimaryBg: palette.white,
	headingText: palette.white,
	ratingButtons: palette.neon_blue,
	startingClimbButton: palette.vice_blue,
	signoutButton: palette.vice_blue,
	textColors: {
		generalText: palette.white,
		paragraphText: palette.white,
	},
	backgroundColors: {
		generalBackground: palette.light_black,
		generalBackgroundGrey: palette.grey,
		generalBackgroundGreyLighter: palette.lighter_grey,
		inputBackground: palette.white,
		climbBackground: palette.vice_grey,
	},
	iconColors: {
		deleteIcon: palette.neon_pink,
		acceptIcon: palette.green,
	},
};
